import { registerEnumType } from '@nestjs/graphql';

export enum formPaymentEnum {
  CASH_PAYMENT = 'PAGAMENTO À VISTA',
  ADVANCE_PAYMENT = 'PAGAMENTO ANTECIPADO',
  PAYMENT_BY_INVOICE = 'PAGAMENTO POR FATURA',
  PAYMENT_BY_BANK_SLIP = 'PAGAMENTO POR BOLETO BANCÁRIO',
  PAYMENT_BY_CREDIT_DEBIT_CARD = 'PAGAMENTO POR CARTÃO DE CRÉDITO/DÉBITO',
  PAYMENT_BY_BANK_TRANSFER = 'PAGAMENTO POR TRANSFERÊNCIA BANCÁRIA',
  PAYMENT_BY_CHECK = 'PAGAMENTO POR CHEQUE',
  CASH_IN_PAYMENT = 'PAGAMENTO EM DINHEIRO',
  PAYMENT_BY_FREIGHT_CARD = 'PAGAMENTO POR MEIO DE CARTÃO DE FRETE',
  PAYMENT_BY_CONSIGNMENT = 'PAGAMENTO POR CONSIGNAÇÃO',
  PAYMENT_BY_PIX = 'PAGAMENTO POR PIX',
}
registerEnumType(formPaymentEnum, { name: 'FormPayment' });
