version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  test-api:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r api/requirements.txt
      - run:
          name: Run tests and collect coverage
          command: pytest --cov api/
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-api
