import { LegalPerson } from 'domain/entities/LegalPerson/LegalPerson';
import { NaturalPerson } from 'domain/entities/NaturalPerson/NaturalPerson';
import { PhysicalCustomerOrder } from 'domain/entities/PhysicalClientEntities/physicalCustomerOrder/PhysicalCustomerOrder';
import { PhysicalCustomerQuoteTable } from 'domain/entities/QuoteTables/PhysicalCustomerQuoteTable/PhysicalCustomerQuoteTable';

import { LegalClientCte } from '../LegalClientCte/LegalClientCte';
import { CtePhyscialCustomerPdf } from './CtePdfPhysicalCustomer';

describe('CarrierCompany', () => {
  it('should create carrier company', () => {
    const cte = new CtePhyscialCustomerPdf({
      carrierCompany: new LegalPerson({
        fantasy_name: 'Empresa ABC',
        cnpj: '12345678000123',
        state_registration: '123456789',
        corporate_name: 'Empresa ABC LTDA',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Sala 456',
        city: 'São Paulo',
        uf: 'SP',
        cep: '4545454',
        first_phone: '11111111111',
        second_phone: '22222222211',
        third_phone: null,
        email: 'empresa@example.com',
      }),
      physicalCustomer: new NaturalPerson({
        name: 'Jão',
        date_birth: new Date(),
        gender: 'Masculino',
        cpf: '147475874747',
        rg: '1234567',
        cep: '12345678',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Apartamento 456',
        city: 'São Paulo',
        uf: 'SP',
        first_phone: '155455',
        second_phone: null,
        third_phone: '333333333',
        email: 'joao@example.com',
        nationality: 'Brasileiro',
      }),
      cteData: new LegalClientCte({
        acessKey: '26.5.65.645.465464654.45.645646546',
        cteNumber: '123456789',
        orderId: '6465465461654',
        id: '56546',
        observations: '464654',
        cteType: '546496',
      }),
      autorizationDate: new Date(),
      orderData: new PhysicalCustomerOrder({
        order: '65465d4as687d984asd987d9as7d9',
        created_by: 'test',
        updated_by: 'test',
        physicalCustomerId: '54564654',
        quote_table_id: '454654',
        carrier_id: '467899',
        expenses: [{ expenseName: 'sadsad', value: 6546 }],
      }),
      quoteData: new PhysicalCustomerQuoteTable({
        amount: 564,
        codQuote: 'aSdasd',
        created_by: 'sdsds',
        description: 'sdasdas',
        mass: 56.55,
        nf_value: 454.747,
        adressDestiny: {
          address_number: '32+65',
          city: '54654',
          neighborhood: '546546',
          postalCod: '1548787',
          street: '646546',
          uf: 'pf',
          complement: '54654654',
        },
        adressOrigin: {
          address_number: '32+65',
          city: '54654',
          neighborhood: '546546',
          postalCod: '1548787',
          street: '646546',
          uf: 'pf',
          complement: '54654654',
        },
        formPayment: 'Pix',
        kindService: 'sadasd',
        recipientId: '546.54.+654.6',
        senderId: '454654654',
        typeMerchandise: '155',
        updated_by: '45654654',
        volume: 54.45,
        who_pays: 'FOB',
      }),
      rntrc: '46546',
      senderLegalPerson: new LegalPerson({
        fantasy_name: 'Empresa ABC',
        cnpj: '12345678000123',
        state_registration: '123456789',
        corporate_name: 'Empresa ABC LTDA',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Sala 456',
        cep: '64646',
        city: 'São Paulo',
        uf: 'SP',
        first_phone: '11111111111',
        second_phone: '22222222211',
        third_phone: null,
        email: 'empresa@example.com',
      }),
      recipientLegalPerson: new LegalPerson({
        fantasy_name: 'Empresa ABC',
        cnpj: '12345678000123',
        cep: '546546',
        state_registration: '123456789',
        corporate_name: 'Empresa ABC LTDA',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Sala 456',
        city: 'São Paulo',
        uf: 'SP',
        first_phone: '11111111111',
        second_phone: '22222222211',
        third_phone: null,
        email: 'empresa@example.com',
      }),
      senderNaturalPerson: new NaturalPerson({
        name: 'Jão',
        date_birth: new Date(),
        gender: 'Masculino',
        cpf: '147475874747',
        rg: '1234567',
        cep: '12345678',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Apartamento 456',
        city: 'São Paulo',
        uf: 'SP',
        first_phone: '155455',
        second_phone: null,
        third_phone: '333333333',
        email: 'joao@example.com',
        nationality: 'Brasileiro',
      }),
      recipientNaturalPerson: new NaturalPerson({
        name: 'Jão',
        date_birth: new Date(),
        gender: 'Masculino',
        cpf: '147475874747',
        rg: '1234567',
        cep: '12345678',
        public_place: 'Rua Principal',
        address_number: '123',
        neighborhood: 'Centro',
        complement: 'Apartamento 456',
        city: 'São Paulo',
        uf: 'SP',
        first_phone: '155455',
        second_phone: null,
        third_phone: '333333333',
        email: 'joao@example.com',
        nationality: 'Brasileiro',
      }),
    });

    expect(cte).toBeTruthy();
  });
});
